askme_pupkin/urls.py
from django.contrib import admin
from django.urls import path

from app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('hot/', views.hot, name='hot'),
    path('settings/', views.settings, name='settings'),
    path('questions/<int:question_id>', views.question, name='question'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('tag/<str:tag>', views.tag, name='tag'),
    path('ask', views.ask, name='ask'),
    path('admin/', admin.site.urls),
]

app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.forms import ModelForm


# Create your models here.

class QuestionManager(models.Manager):
    def get_new(self):
        return Question.objects.order_by('-created_at')

    def get_hot(self):
        return Question.objects.order_by('-rating', 'created_at')

    def get_by_tag(self, tag):
        tag_id = Tag.objects.get(name=tag).id
        return self.filter(tags=tag_id)


class AnswerManager(models.Model):
    def get_answers(self, question):
        return Answer.objects.filter(question=question).order_by('-rating', 'created_at')


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    name = models.CharField(max_length=100, null=False, blank=False)
    avatar = models.ImageField(null=True, blank=True)
    rating = models.PositiveSmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Question(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True)
    rating = models.PositiveSmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = QuestionManager()

    def __str__(self):
        return self.title


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    correct = models.BooleanField(default=False)
    rating = models.PositiveSmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    object = AnswerManager()

    def __str__(self):
        return self.content


class QuestionLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (('user', 'question'),)

    def __str__(self):
        return self.user.username


class AnswerLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (('user', 'answer'),)

    def __str__(self):
        return self.user.username

templates/layouts/answer.html
{% load static %}

{% block content %}
    <article class="card mb-3 border-secondary">
        <div class="row">
            <div class="col-2 p-2">
                <div class="row">
                    <div class="col-md-12 d-flex justify-content-center">
                        <div style="height: 95px">
                            <img src="{% static 'img/' %}{{ answer.user.profile.avatar }}"
                                 style="max-width: 90px;"
                                 onerror="this.onerror=null; this.src='{% static 'img/default.jpg' %}';"
                                 alt="..."/>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 d-flex justify-content-center">
                        <nav aria-label="Page navigation">
                            <ul class="pagination">
                                <li class="page-item active"><a class="page-link" href="#">+</a></li>
                                <li class="page-item disabled"><a class="page-link"
                                                                  href="#">{{ answer.answerlike_set.all.count }}</a>
                                </li>
                                <li class="page-item"><a class="page-link" href="#">-</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="mt-2">
                    <p class="ms-0">{{ answer.content }}</p>
                    <div class="form-check">
                        <input class="form-check-input {% if  answer.correct %}checked{% endif %}" type="checkbox"
                               value="">
                        <label class="form-check-label" for="defaultCheck1">Correct!</label>
                    </div>
                </div>
            </div>
        </div>
    </article>
{% endblock %}

templates/layouts/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>AskPupkin</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"/>
    {#    <link rel="stylesheet" href="{% static 'bootstrap-5.3.3-dist/css/bootstrap.min.css' %}">#}
    <link rel="stylesheet" href="{% static 'css/application.css' %}"/>
</head>

<body>
<header>
    <nav class="navbar bg-body-tertiary">
        <div class="container-sm-fluid container-lg">
            <a class="navbar-brand" href="{% url 'index' %}">AskPupkin</a>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
                <button class="btn btn-success" type="submit">Search</button>
            </form>
            {% if user.is_authenticated %}
                <div class="d-flex justify-content-between gap-3">
                    <div class="border">
                        <img src="{% static 'img/' %}{{ user.profile.avatar }}" width="50" height="50"
                             onerror="this.onerror=null; this.src='{% static 'img/default.jpg' %}';" alt="..."/>
                    </div>
                    <div class="d-flex flex-column justify-content-between">
                        <div>{{ user.username }}</div>
                        <div><a class="link-offset-2 link-underline link-underline-opacity-0"
                                href="{% url 'settings' %}">Settings</a>
                            <a class="link-danger link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover"
                               href="{% url 'logout' %}">Log out</a>
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="d-flex justify-content-between gap-3">
                    <div class="d-flex flex-column justify-content-between">
                        <div>
                            <a href="{% url 'login' %}">Log in</a>
                            <a href="{% url 'signup' %}">Sign up</a>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </nav>
</header>

<main class="container-fluid container-lg mt-3 mb-5">
    <div class="row">
        {% block content %}
        {% endblock %}

        <div class="col-3 mt-5">
            <h3>Popular Tags</h3>
            <div class="row">
                <div class="col">
                    {% for tag in popular_tags %}
                        <a class="btn btn-outline-{{ tag.color }} p-1 m-1" href="{% url 'tag' tag %}">{{ tag }}</a>
                    {% endfor %}
                </div>
            </div>
            <h3 class="mt-5">Best Members</h3>
            <div>
                {% for member in members %}
{#                    <a href="#" class="d-block mb-1">{{ member.user.username }}</a>#}
                    <h5 class="m-1 ms-4">{{ member.user.username }}</h5>
                {% endfor %}
            </div>
        </div>
    </div>
</main>
<footer class="footer sticky-bottom p-3 bg-light">
    <div class="container">
        <span class="text-muted">© 2024 All rights reserved. No giraffes were harmed in the making of this website 🦒</span>
    </div>
</footer>
</body>
</html>

templates/layouts/pagination.html
{% if page_obj.has_other_pages %}
    {% with prev=page_obj.has_previous next=page_obj.has_next last=page_obj.paginator.num_pages %}
        <nav aria-label="Page navigation">
            <ul class="pagination">
                <li class="page-item">
                    <a class="page-link" href="?page=1"> << </a>
                </li>

                <li class="page-item {% if not prev %} disabled {% endif %}">
                    <a class="page-link" href="?page={% if prev %}{{ page_obj.previous_page_number }}{% endif %}">
                        < </a>
                </li>

                {% if page_obj.number > 2 %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1">1</a>
                    </li>
                    {% if page_obj.number > 3 %}
                        <li class="page-item">
                            <a class="page-link" href="?page=2">2</a>
                        </li>
                    {% endif %}
                {% endif %}

                {% if page_obj.number > 4 %}
                    <li class="page-item disabled"><span class="page-link">...</span></li>
                {% endif %}

                {% if page_obj.number > 1 %}
                    <li class="page-item">
                        <a class="page-link"
                           href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                    </li>
                {% endif %}

                <li class="page-item active">
                    <a class="page-link" href="?page={{ page_obj.number }}"> {{ page_obj.number }} </a>
                </li>

                {% if until_last > 0 %}
                    <li class="page-item">
                        <a class="page-link"
                           href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                    </li>
                {% endif %}

                {% if until_last > 2 %}
                    <li class="page-item disabled"><span class="page-link">...</span></li>
                {% endif %}

                {% if until_last > 1 %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ last }}"> {{ last }} </a>
                    </li>
                {% endif %}

                <li class="page-item {% if not next %} disabled {% endif %}">
                    <a class="page-link" href="?page={% if next %}{{ page_obj.next_page_number }}{% endif %}">
                        > </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ last }}"> >> </a>
                </li>
            </ul>
        </nav>
    {% endwith %}
{% endif %}

templates/layouts/question.html
{% load static %}
<article class="card mb-4 w-100">
    <div class="row g-0">
        <div class="col-2 p-2">
            <div class="row">
                <div class="col-md-12 d-flex justify-content-center">
                    <div style="height: 95px">
                        <img src="{% static 'img/' %}{{ question.user.profile.avatar }}"
                             style="max-width: 90px;"
                             onerror="this.onerror=null; this.src='{% static 'img/default.jpg' %}';"
                             alt="..."/>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 d-flex justify-content-center">
                    <nav aria-label="Page navigation">
                        <ul class="pagination">
                            <li class="page-item active"><a class="page-link" href="#">+</a></li>
                            <li class="page-item disabled"><a class="page-link"
                                                              href="#">{{ question.questionlike_set.all.count }}</a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">-</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card-body">
                <h5 class="card-title">
                    <a class="link-offset-2 link-underline link-underline-opacity-0"
                       href="{% url 'question' question.id %}">{{ question.title }}</a>
                </h5>
                <p class="card-text">
                    {{ question.content }}
                </p>
                <div class="row">
                    <a class="col-4 link-offset-2 link-underline link-underline-opacity-0"
                       href="{% url 'question' question.id %}">answers
                        ({{ question.answer_set.all.count }})</a>
                    <div class="col-8">
                        <span>Tags</span>
                        {% for tag in question.tags.all %}
                            <a class="btn btn-outline-primary btn-sm" href="{% url 'tag' tag %}">{{ tag }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</article>